### PR TITLE
added feature for saving to pcd

### PR DESCRIPTION
**Pull request by rdube**
@helenol @lorenwel I added a service for saving the point_cloud in pcd format.

### CODE REVIEW

**Comment by lorenwel** [comment]
Nice, thanks!

**Comment by rdube** [comment]
@helenol any comments on that small add-on?

**Comment by helenol** [comment]
I hate PCD and much prefer PLY (not crappy proprietary PCL format, other viewers actually open it), but otherwise LGTM. (PCL can also read/write PLY). Especially since you guys seem to use PCD everywhere. ;)

@rdube @lorenwel

**Comment by rdube** [comment]
Cool thanks!! Ok we will change to PLY then!! :-)

**Comment by helenol** [comment]
Weird Jenkins issues... Failing since there's no unit tests in a package. Wtf.
test this please

**Comment by helenol** [comment]
test this please

**Pull request merged**
