### PR TITLE
Made pcl_pub_ use latch_topic_ parameter.

### PR DESCRIPTION
**Pull request by lorenwel**
If this was not an oversight but intentional feel free to just close this commit.

### CODE REVIEW

**Comment by helenol** [comment]
This was intentional as this shouldn't query the Tf tree/etc. by default unless this information is actually being used by someone (other topics just use the state of the map, but this actually uses the state of the drone as well -- so doesn't make much sense to latch.)
Let me know what you think about this!

**Comment by lorenwel** [comment]
I would like to use the published point cloud for visualization of the octomap since a MarkerArray slows Rviz down a lot. For this purpose a latching topic would be nice.
I understand your argument, though. You should decide whether the performance hit is worth having the extra convenience of a latching topic. 
I can make do either way.

A different but kind of related question: My understanding is that pcl_pub_ is supposed to publish the octomap as a point cloud. Shouldn't pcl_pub_ then publish the voxels that are outside of the robot bounding box, not inside? Or is this publisher somehow related to collision detection?

**Comment by helenol** [comment]
Ah then we should just make a publisher for the marker centers, not in the surroundings of current  drone. :)

Maybe change pcl_pub_ to `nearest_obstacle_pub_` or something and make pcl_pub_ publish the whole octomap as a pointcloud, I think this would make more sense.

**Comment by rdube** [comment]
+1 for the latest proposition :)

**Comment by lorenwel** [comment]
Agreed, that makes sense.

**Comment by lorenwel** [comment]
Added the mentioned changes in #59

**Pull request closed without merging**
